mutation CreateUser($displayName: String!, $email: String!, $ufrjId: String) @auth(level: USER) {
  user_insert(data: {displayName: $displayName, email: $email, ufrjId: $ufrjId})
}

query ListActivitiesForEventDay($eventDayId: UUID!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  activities(where: {eventDayId: {eq: $eventDayId}}) {
    id
    title
    description
    startTime
    endTime
    location
    capacity
  }
}

mutation RegisterUserForActivity($activityId: UUID!) @auth(level: USER) {
  registration_insert(data: {activityId: $activityId, userId_expr: "auth.uid", registeredAt_expr: "request.time", status: "registered"})
}

query GetUserProfile @auth(level: USER) {
  user(key: {id_expr: "auth.uid"}) {
    id
    displayName
    email
    ufrjId
    photoUrl
    isOrganizer
  }
}